# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fast.sum.integer <- function(xx) {
    .Call('plyrmr_fast_sum_integer', PACKAGE = 'plyrmr', xx)
}

fast.sum.numeric <- function(xx) {
    .Call('plyrmr_fast_sum_numeric', PACKAGE = 'plyrmr', xx)
}

fast.mean.integer <- function(xx) {
    .Call('plyrmr_fast_mean_integer', PACKAGE = 'plyrmr', xx)
}

fast.mean.numeric <- function(xx) {
    .Call('plyrmr_fast_mean_numeric', PACKAGE = 'plyrmr', xx)
}

fast.first.integer <- function(xx) {
    .Call('plyrmr_fast_first_integer', PACKAGE = 'plyrmr', xx)
}

fast.first.numeric <- function(xx) {
    .Call('plyrmr_fast_first_numeric', PACKAGE = 'plyrmr', xx)
}

fast.first.character <- function(xx) {
    .Call('plyrmr_fast_first_character', PACKAGE = 'plyrmr', xx)
}

fast.first.factor <- function(xx) {
    .Call('plyrmr_fast_first_factor', PACKAGE = 'plyrmr', xx)
}

fast.first.logical <- function(xx) {
    .Call('plyrmr_fast_first_logical', PACKAGE = 'plyrmr', xx)
}

